version: '3.1'
services:
  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  web:
    build:
      context: ./go
    ports:
      - "8080:8080"
    volumes:
      - ./go:/go/src
    depends_on:
        - db
